language: java

jdk:
  - openjdk8

services:
  - mysql

jobs:
  include:
  - env:
      - OPENMRS_VERSION=1.7.4
      - PROFILE='-Ppre-1.9'
      - FILE_SUFFIX=1_7
  - env:
      - OPENMRS_VERSION=1.8.3
      - PROFILE='-Ppre-1.9'
      - FILE_SUFFIX=1_8
  - env:
      - OPENMRS_VERSION=1.9.12
      - PROFILE=''
      - FILE_SUFFIX=1_9
  - env:
      - OPENMRS_VERSION=1.10.2
      - PROFILE=''
      - FILE_SUFFIX=1_10
  - env:
      - OPENMRS_VERSION=1.11.4
      - PROFILE=''
      - FILE_SUFFIX=1_11
  - env:
      - OPENMRS_VERSION=2.0.1
      - PROFILE=''
      - FILE_SUFFIX=2_0
  - env:
      - OPENMRS_VERSION=2.1.0
      - PROFILE=''
      - FILE_SUFFIX=2_1
  - env:
      - OPENMRS_VERSION=2.2.0
      - PROFILE=''
      - FILE_SUFFIX=2_2
  - env:
      - OPENMRS_VERSION=2.3.0
      - PROFILE=''
      - FILE_SUFFIX=2_3
  - env:
      - OPENMRS_VERSION=2.4.5
      - PROFILE=''
      - FILE_SUFFIX=2_4
      - TWO_STEP=true
  - env:
      - OPENMRS_VERSION=2.5.5
      - PROFILE=''
      - FILE_SUFFIX=2_5
      - TWO_STEP=true

install: true

script: bash upgrade_mvp.sh
  
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - "openmrs_concepts_1_7.zip"
    - "openmrs_concepts_1_8.zip"
    - "openmrs_concepts_1_9.zip"
    - "openmrs_concepts_1_10.zip"
    - "openmrs_concepts_1_11.zip"
    - "openmrs_concepts_2_0.zip"
    - "openmrs_concepts_2_1.zip"
    - "openmrs_concepts_2_2.zip"
    - "openmrs_concepts_2_3.zip"
    - "openmrs_concepts_2_4.zip"
    - "openmrs_concepts_2_5.zip"
  skip_cleanup: true
  on:
    tags: true
