language: java

jdk:
  - oraclejdk8

services:
  - mysql

before_install:
  - mysql -e "create database IF NOT EXISTS liquibaserunner;" -uroot

script:
  - mvn install -Dtest=UpgradeMVPTest -DfailIfNoTests=false -Dopenmrs.version="2.0.1" -Ddb.user="root" -Ddb.password="" -Dmvp.file="openmrs_concepts_1_6.sql"
  - mysqldump -uroot liquibaserunner > openmrs_concepts_2_0.sql

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: "openmrs_concepts_2_0.sql"
  skip_cleanup: true
  on:
    tags: true
