language: java

jdk:
  - openjdk8

services:
  - mysql

jobs:
  include:
  - env:
      - OPENMRS_VERSION=1.7.4
      - PROFILE='-Ppre-1.9'
      - FILE_SUFFIX=1_7
  - env:
      - OPENMRS_VERSION=1.8.3
      - PROFILE='-Ppre-1.9'
      - FILE_SUFFIX=1_8
  - env:
      - OPENMRS_VERSION=1.9.12
      - PROFILE=''
      - FILE_SUFFIX=1_9
  - env:
      - OPENMRS_VERSION=1.10.2
      - PROFILE=''
      - FILE_SUFFIX=1_10
  - env:
      - OPENMRS_VERSION=1.11.4
      - PROFILE=''
      - FILE_SUFFIX=1_11
  - env:
      - OPENMRS_VERSION=2.0.1
      - PROFILE=''
      - FILE_SUFFIX=2_0
  - env:
      - OPENMRS_VERSION=2.1.0
      - PROFILE=''
      - FILE_SUFFIX=2_1
  - env:
      - OPENMRS_VERSION=2.2.0
      - PROFILE=''
      - FILE_SUFFIX=2_2
  - env:
      - OPENMRS_VERSION=2.3.0
      - PROFILE=''
      - FILE_SUFFIX=2_3
  - env:
      - OPENMRS_VERSION=2.4.5
      - PROFILE=''
      - FILE_SUFFIX=2_4
  - env:
      - OPENMRS_VERSION=2.5.5
      - PROFILE=''
      - FILE_SUFFIX=2_5

install: true

script:
  - mysql -e "CREATE DATABASE IF NOT EXISTS liquibaserunner CHARACTER SET utf8 COLLATE utf8_general_ci;" -uroot
  - mysql -e "SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));" -uroot
  - mvn install -q $PROFILE -Dtest=UpgradeMVPTest -DfailIfNoTests=false -Dopenmrs.version="$OPENMRS_VERSION" -Ddb.user="root" -Ddb.password="" -Dmvp.file="$TRAVIS_BUILD_DIR/openmrs_concepts_1_6.zip"
  - mysqldump -uroot liquibaserunner > "openmrs_concepts_$FILE_SUFFIX.sql"
  - zip "openmrs_concepts_$FILE_SUFFIX.zip" "openmrs_concepts_$FILE_SUFFIX.sql"
  
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - "openmrs_concepts_1_7.zip"
    - "openmrs_concepts_1_8.zip"
    - "openmrs_concepts_1_9.zip"
    - "openmrs_concepts_1_10.zip"
    - "openmrs_concepts_1_11.zip"
    - "openmrs_concepts_2_0.zip"
    - "openmrs_concepts_2_1.zip"
    - "openmrs_concepts_2_2.zip"
    - "openmrs_concepts_2_3.zip"
    - "openmrs_concepts_2_4.zip"
    - "openmrs_concepts_2_5.zip"
  skip_cleanup: true
  on:
    tags: true
